name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

permissions:
  contents: write

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - name: Update README with metrics
        uses: anmol098/waka-readme-stats@master
        env:
          GIT_CONFIG_COUNT: "2"
          GIT_CONFIG_KEY_0: credential.helper
          GIT_CONFIG_VALUE_0: ""
          GIT_CONFIG_KEY_1: credential.helper
          GIT_CONFIG_VALUE_1: '!f() { echo username=x-access-token; echo "password=$INPUT_GH_TOKEN"; }; f'
          GIT_TERMINAL_PROMPT: "0"
          INPUT_GH_USER: ${{ github.repository_owner }}
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ github.token }}
          SHOW_UPDATED_DATE: "True"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_COMMIT: "True"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_SHORT_INFO: "False"
          SHOW_LINES_OF_CODE: "False"
          SHOW_LOC_CHART: "False"
          SHOW_TOTAL_CODE_TIME: "False"
          SHOW_LANGUAGE: "True"
          SHOW_OS: "True"
          SHOW_TIMEZONE: "False"
          SHOW_EDITORS: "True"
          SHOW_PROJECTS: "False"
          SHOW_LANGUAGE_PER_REPO: "False"
          SYMBOL_VERSION: "2"
